spring:
  datasource:
     driver-class-name: com.mysql.cj.jdbc.Driver
     #root
     username: root
     password: _lzxQQ2270
     #localhost
     url: jdbc:mysql://123.57.80.206:3306/blog?useUnicode=true&allowMultiQueries=true&characterEncoding=UTF-8&serverTimezone=UTC

mybatis:
  type-aliases-package: com.lot.blog.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true #设置返回字段不为空，前端不报错

logging:
  level:
    root: warn
    com.lot: info
  file:
    path: log/blog-pro.log
server:
  port: 8081
